/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExpenseCharts: typeof import('./src/components/ExpenseCharts.vue')['default']
    ExpenseList: typeof import('./src/components/ExpenseList.vue')['default']
    ExpensePagination: typeof import('./src/components/ExpensePagination.vue')['default']
    ExpenseSearch: typeof import('./src/components/ExpenseSearch.vue')['default']
    ExpenseStats: typeof import('./src/components/ExpenseStats.vue')['default']
    ExpenseTable: typeof import('./src/components/ExpenseTable.vue')['default']
    ExportButton: typeof import('./src/components/ExportButton.vue')['default']
    GlassAlert: typeof import('./src/components/GlassAlert.vue')['default']
    GlassButton: typeof import('./src/components/GlassButton.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    GlassCheckbox: typeof import('./src/components/GlassCheckbox.vue')['default']
    GlassDialog: typeof import('./src/components/GlassDialog.vue')['default']
    GlassForm: typeof import('./src/components/GlassForm.vue')['default']
    GlassFormItem: typeof import('./src/components/GlassFormItem.vue')['default']
    GlassInput: typeof import('./src/components/GlassInput.vue')['default']
    GlassInputNumber: typeof import('./src/components/GlassInputNumber.vue')['default']
    GlassMessage: typeof import('./src/components/GlassMessage.vue')['default']
    GlassmorphismComponent: typeof import('./src/components/GlassmorphismComponent.vue')['default']
    GlassSlider: typeof import('./src/components/GlassSlider.vue')['default']
    GlassSwitch: typeof import('./src/components/GlassSwitch.vue')['default']
    GlassTable: typeof import('./src/components/GlassTable.vue')['default']
    GlassTableColumn: typeof import('./src/components/GlassTableColumn.vue')['default']
    GlassUpload: typeof import('./src/components/GlassUpload.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MarkdownDialog: typeof import('./src/components/MarkdownDialog.vue')['default']
    MessageTip: typeof import('./src/components/MessageTip.vue')['default']
    PredictionDropdown: typeof import('./src/components/PredictionDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpendingLimitDisplay: typeof import('./src/components/SpendingLimitDisplay.vue')['default']
    SpendingLimitSetting: typeof import('./src/components/SpendingLimitSetting.vue')['default']
  }
}
