/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExpenseCharts: typeof import('./src/components/ExpenseCharts.vue')['default']
    ExpenseList: typeof import('./src/components/ExpenseList.vue')['default']
    ExpensePagination: typeof import('./src/components/ExpensePagination.vue')['default']
    ExpenseSearch: typeof import('./src/components/ExpenseSearch.vue')['default']
    ExpenseStats: typeof import('./src/components/ExpenseStats.vue')['default']
    ExpenseTable: typeof import('./src/components/ExpenseTable.vue')['default']
    ExportButton: typeof import('./src/components/ExportButton.vue')['default']
    GlassButton: typeof import('./src/components/GlassButton.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    GlassInput: typeof import('./src/components/GlassInput.vue')['default']
    GlassmorphismComponent: typeof import('./src/components/GlassmorphismComponent.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MarkdownDialog: typeof import('./src/components/MarkdownDialog.vue')['default']
    MessageTip: typeof import('./src/components/MessageTip.vue')['default']
    PredictionDropdown: typeof import('./src/components/PredictionDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpendingLimitDisplay: typeof import('./src/components/SpendingLimitDisplay.vue')['default']
    SpendingLimitSetting: typeof import('./src/components/SpendingLimitSetting.vue')['default']
  }
}
