name: Code Lines Count
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
      - name: Install cloc
        run: sudo apt-get install -y cloc
      - name: Count lines in android
        run: cloc android
      - name: Count lines in client/src
        run: cloc client/src
      - name: Count lines in server/src
        run: cloc server/src
      - name: Count lines in server-go
        run: cloc server-go
